version: '3'

services:
  app:  
    build: './src/app'
    volumes:
      - './src/app:/app'

  github-release:
    image: 'github-release'
    build: './src/app'

  docker-push:
    image: 'tmvdl/projects:sconomy'
    build: './src/app'
