version: '3'

services:
  app:  
    build: './src/app'
    volumes:
      - './src/app/html:/usr/share/nginx/html'

  github-release:
    image: 'github-release'
    build: './src/app'

  docker-push:
    image: 'tmvdl/projects:money'
    build: './src/app'
